[package]
name = "service_utils_rs"
version = "0.1.3"
edition = "2021"
authors = ["code-serenade <arthas.you@163.com>"]
description = "A brief description of your crate"
repository = "https://github.com/code-serenade/service_utils_rs"
homepage = "https://github.com/code-serenade/service_utils_rs"
license = "MIT"
documentation = "https://docs.rs/service_utils_rs"

[dependencies]
byteorder = "1.5.0"
bytes = "1.7.1"
chrono = "0.4.38"
config = "0.15"
futures-util = "0.3.30"
jsonwebtoken = { version = "9.3.0", optional = true }
serde = { version = "1.0.204", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26"
reqwest = { version = "0.12.12", features = ["json"] }
url = "2.2"
indexmap = "2.7"
serde_json = "1.0"

[features]
jwt = ["jsonwebtoken"]

full = ["jwt"]

[package.metadata.docs.rs]
features = ["jwt"]


