[package]
name = "service_utils_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
jsonwebtoken = { version = "9.3.0", optional = true }
serde = { version = "1.0.204", features = ["derive"] }
thiserror = "1.0.63"

[features]
jwt = ["jsonwebtoken"]

full = ["jwt"]

